pizzeria-application:
  replicaCount: 1
  image:
    repository: baloiseincubator/pizzeria-application
    tag: 0b113b032ff24e85947057f4aa1a8f0187ec49b4
  network:
    http:
      servicePort: 8080
      ingress:
        host: pizzeria-application.cloud.baloise.dev
  env:
    - name: menu-service.url
      value: http://menu-service.menu-service:8080
    - name: stock-service.url
      value: http://stock-service.stock-service:8080
  annotations:
    sidecar.istio.io/inject: "true"
