pizzeria-application:
  replicaCount: 1
  image:
    repository: baloiseincubator/pizzeria-application
    tag: 5ec41d14424cf26556c3f2b3e736e992a91f4ad2
  network:
    http:
      servicePort: 8080
      ingress:
        host: pizzeria-application.cloud.baloise.dev
  env:
    - name: menu-service.url
      value: http://menu-service.menu-service:8080
    - name: stock-service.url
      value: http://stock-service.stock-service:8080
#  annotations:
#    sidecar.istio.io/inject: "true"
  labels:
    maistra.io/expose-route: 'true'