menu-service:
  replicaCount: 1
  image:
    repository: baloiseincubator/menu-service
    tag: 4b93ebad99b5a1733e112b00b6e732eeeb38ff92
  network:
    http:
      servicePort: 8080
      ingress:
        host: menu-service.cloud.baloise.dev