menu-service:
  replicaCount: 1
  image:
    repository: baloiseincubator/menu-service
    tag: eb025f6e2b3ae35de3fa66f402faea1f51803155
  network:
    http:
      servicePort: 8080
      ingress:
        host: menu-service.cloud.baloise.dev
  #annotations:
    #sidecar.istio.io/inject: "true"
  labels:
    maistra.io/expose-route: 'true'