menu-service:
  replicaCount: 1
  image:
    repository: baloiseincubator/menu-service
    tag: df489aeee2dd0a42ba9acf5049e476245a9420e9
  network:
    http:
      servicePort: 8080
      ingress:
        host: menu-service-42815cc3.apps.okd.baloise.dev
