pizzeria-application:
  replicaCount: 1
  image:
    repository: baloiseincubator/pizzeria-application
    tag: 4de63fe08d551e123270d645fc9373e32890dd99
  network:
    http:
      servicePort: 8080
      ingress:
        host: pizzeria-application-ae660ed9.apps.okd.baloise.dev
  env:
  - name: menu-service.url
    value: http://menu-service.menu-service:8080
  - name: stock-service.url
    value: http://stock-service.stock-service:8080
