stock-service:
  replicaCount: 1
  image:
    repository: baloiseincubator/stock-service
    tag: 9d324c7b8ee8dbe025176084eaf70f0d1e42ec9d
  network:
    http:
      servicePort: 8080
      ingress:
        host: stock-service.cloud.baloise.dev