stock-service:
  replicaCount: 1
  image:
    repository: baloiseincubator/stock-service
    tag: 1207302864d90c988ce4f3b109cb2c73baed514f
  network:
    http:
      servicePort: 8080
      ingress:
        host: stock-service.cloud.baloise.dev