stock-service:
  replicaCount: 1
  image:
    repository: baloiseincubator/stock-service
    tag: 8aa686d3fb9a36bcd517a00b82f55fe8866cd91b
  network:
    http:
      servicePort: 8080
      ingress:
        host: stock-service.cloud.baloise.dev
  labels:
