pizzeria-application:
  replicaCount: 1
  image:
    repository: baloiseincubator/pizzeria-application
    tag: c0209f1e82ec3d5d736856a5a3467f139647bd3f
  network:
    http:
      servicePort: 8080
      ingress:
        host: pizzeria-application-4678918c.apps.okd.baloise.dev
  env:
  - name: menu-service.url
    value: http://menu-service.menu-service:8080
  - name: stock-service.url
    value: http://stock-service.stock-service:8080
